final - dev to prod
pandacover/tekion-menu pull request #2
Opened 2023-02-27 06:31 UTC by pandacover

2023-03-01 05:44 UTC, somethinglikejohn commented on public/robots.txt
> +User-agent: *
remove files which are not used or required by the requirements defined.

2023-03-01 05:46 UTC, somethinglikejohn commented on src/App.jsx
> +    const cartLocalStorage = JSON.parse(localStorage.getItem("cart"));
perform the localstorage access and parse in 2 differnt lines

2023-03-01 05:46 UTC, somethinglikejohn commented on src/App.jsx
> +    const cartLocalStorage = JSON.parse(localStorage.getItem("cart"));
Also place them in a try catch and you can supply the default values there instead of the useState

2023-03-01 06:23 UTC, somethinglikejohn requested changes

2023-03-01 06:23 UTC, somethinglikejohn commented on src/components/loader/loader.jsx
> +import "../../styles/loader.css";
move the css used in this file to a file placed under same folder

loader
   .jsx
   .css
   .utils.js
   .helpers.js
   .constants.js ........

2023-03-01 06:23 UTC, somethinglikejohn commented on src/components/menu/actions/add-button.jsx
> +  onAdd: function(){},
make a global noop const or use https://lodash.com/docs/4.17.15#noop

2023-03-01 06:23 UTC, somethinglikejohn commented on src/components/menu/actions/edit-button.jsx
> +const EditButton = ({ quantity = 0, editQuantity, onInputQuant }) => {
https://reactjs.org/docs/typechecking-with-proptypes.html#default-prop-values

2023-03-01 06:23 UTC, somethinglikejohn commented on src/components/menu/actions/edit-button.jsx
> +    editQuantity: function(){},
noop

2023-03-01 06:23 UTC, somethinglikejohn commented on src/components/menu/card.jsx
> +// import LazyImg from "../lazy-image/lazyimg";
remove if not  needed

2023-03-01 06:23 UTC, somethinglikejohn commented on src/components/menu/cart-icon.jsx
> +          {cartItems.reduce((a, b) => a + b.count, 0)}
move this function out of the templating - prepare the value and use it here

2023-03-01 06:23 UTC, somethinglikejohn commented on src/components/menu/cart-icon.jsx
> +      {cartItems.length > 0 && (
try using a function to prepare this section of jsx and then use the value here

2023-03-01 06:23 UTC, somethinglikejohn commented on src/components/menu/filter.jsx
> +              onChange={() => setFilter("VEG")}
avoid inline functions - move them up - it may be one liners , avoid them as much as possible.

2023-03-01 06:23 UTC, somethinglikejohn commented on src/components/menu/menu-action.jsx
> +import { useCartContext } from "../../contexts/cart.context";
organise imports properly

2023-03-01 06:23 UTC, somethinglikejohn commented on src/components/menu/menu-action.jsx
> +      {!cartItem ? (
we can avoid ternary op here

```
if (!cartItems) {
retuen <AddButton />
}

return <EditButton />
```

2023-03-01 06:23 UTC, somethinglikejohn commented on src/components/menu/filter.jsx
> +              onChange={() => setFilter("NON VEG")}
we can make filternames as an enum and move it to some constants file and use it in various files

2023-03-01 06:23 UTC, somethinglikejohn commented on src/components/menu/menu.jsx
> +import "../../styles/menu.css";
co-locate css

2023-03-01 06:23 UTC, somethinglikejohn commented on src/components/menu/menu.jsx
> +    if (filter === "ALL") document.querySelector("#all").checked = true;
use enums for ALL (filters)

2023-03-01 06:23 UTC, somethinglikejohn commented on src/components/menu/menu.jsx
> +        {menuDataState.map((item) => (
make a function renderCards in this component and move logic into it

2023-03-01 06:23 UTC, somethinglikejohn commented on src/lib/updateArray.js
> +    updateCartLocalStorage(cartArray);
Do not add localstorage logic in the util

2023-03-01 06:23 UTC, somethinglikejohn commented on src/lib/updateArray.js
> +export const removeElement = (array, element) => {
shouldn't this be sufficient ? also what is the use of the last else case ?

`export const removeElement = (list, element) => {
    const elementFromList = list.filter(el => el.id !== element.id);
}`

2023-03-01 06:23 UTC, somethinglikejohn commented on src/pages/CartPage.jsx
> +      <div className={`payment-message ${(success || error) && "show" }`} data-success={success && true} data-error={error && true}>
prepare the classnames outside the template. Same with other attributes

2023-03-01 06:23 UTC, somethinglikejohn commented on src/pages/CartPage.jsx
> +        { success ? success : error }
move status preparation outside template

2023-03-01 06:59 UTC, pandacover commented on public/robots.txt
> +User-agent: *
done

2023-03-01 07:01 UTC, pandacover commented on src/App.jsx
> +    const cartLocalStorage = JSON.parse(localStorage.getItem("cart"));
used useEffect to initialize the cartItems state with items saved in localstorage, and to (re)-initialize it with an empty array if item not available in LS.

2023-03-01 07:03 UTC, pandacover commented on src/components/cart/cart.jsx
> +import { useCartContext } from "../../contexts/cart.context";
It reverted back to small case when I squashed the commits. It's fixed now (smh).

2023-03-01 13:41 UTC, pandacover commented on src/pages/CartPage.jsx
> +      <div className={`payment-message ${(success || error) && "show" }`} data-success={success && true} data-error={error && true}>
done

2023-03-01 13:41 UTC, pandacover commented on src/pages/CartPage.jsx
> +        { success ? success : error }
done

2023-03-01 13:46 UTC, pandacover commented on src/lib/updateArray.js
> +    updateCartLocalStorage(cartArray);
done

2023-03-01 13:48 UTC, pandacover commented on src/components/menu/menu.jsx
> +import "../../styles/menu.css";
done

2023-03-01 13:54 UTC, pandacover commented on src/components/menu/cart-icon.jsx
> +      {cartItems.length > 0 && (
done

2023-03-01 13:56 UTC, pandacover commented on src/components/cart/cart.jsx
> +import "../../styles/cart.css";
done

2023-03-02 03:12 UTC, pandacover commented on src/components/menu/menu.jsx
> +    if (filter === "ALL") document.querySelector("#all").checked = true;
created an enum for all the filters. done

2023-03-02 03:12 UTC, pandacover commented on src/components/menu/filter.jsx
> +              onChange={() => setFilter("NON VEG")}
done

2023-03-02 03:19 UTC, pandacover commented on src/lib/updateArray.js
> +export const removeElement = (array, element) => {
No, since we don't want to remove the element from the list if the user only removes one element from the cart.
```
cartItems = [
    { id, name, type, **count**: 10 },
    ...
]
```
If removeElement is triggered then the `count` property should decrease by 1 and if the item count is equal to 1 then we remove the element from the array itself.

2023-03-02 03:41 UTC, somethinglikejohn commented on src/components/cart/ButtonLink.jsx
> +  return (
shouldn't both if and return have same alignment ?

2023-03-02 03:42 UTC, somethinglikejohn commented on src/components/cart/CartEmpty.jsx
> +import "../../styles/cart-empty.css";
css for this file should be in cart folder itself - modular access

2023-03-02 03:44 UTC, somethinglikejohn commented on src/components/cart/CartUtility.jsx
> +      setSuccess("Thank you for shopping with us!")
setSuccess - should set true or success if you want an enum. Thank you for shopping with us! should be a const in actual code - but lets leave it like this for now.

2023-03-02 03:53 UTC, somethinglikejohn commented on src/components/cart/cart.jsx
> +import "../../styles/cart.css";
i dont see the changes - has all the updates been pushed to remote ?

2023-03-06 06:08 UTC, somethinglikejohn commented on src/components/cart/ButtonLink.jsx
> +  if (classname === "cart-goto-pay" && cartItems.length <= 0) return;
it is not a good practice to check using css class name. A different logic should be used to identify intention.

2023-03-06 06:24 UTC, somethinglikejohn approved these changes

2023-03-06 06:24 UTC, somethinglikejohn commented on src/components/cart/TableRow.jsx
> +        {typeof price === "number" ? `$${price}` : price}
we can avoid this computation here - prepare the value before return and use it in the jsx as much as possible.

2023-03-06 06:24 UTC, somethinglikejohn commented on src/components/cart/ThankMsg.jsx
> +    if(isPurchase) return;
add a newline after this line.

2023-03-06 06:24 UTC, somethinglikejohn commented on src/components/cart/cart-empty/CartEmpty.jsx
> +        <CartX />
why suffix X to Cart ?

2023-03-06 06:24 UTC, somethinglikejohn commented on src/components/cart/cart.jsx
> +  const totalItems = useMemo(
these functions for calculations can be moved to helper files.

const totalItems  = useMemo(() => getItemsTotal(cartItem),[cartItem]); // cleaner component

similarly for getTotalCost();

2023-03-06 06:24 UTC, somethinglikejohn commented on src/components/loader/loader.jsx
> +  return (
add a newline in line 6 ie, before return

2023-03-06 06:46 UTC, pandacover commented on src/components/cart/cart-empty/CartEmpty.jsx
> +        <CartX />
"x" as an icon usually means to close/clear, so as to show that the cart icon denotes an empty cart, I suffixed it with an "X".

2023-03-07 05:50 UTC, somethinglikejohn approved these changes
The remaining comments can be handled in the next PR. Approving this one.

2023-03-07 05:50 UTC, merged

2023-03-09 09:39 UTC, somethinglikejohn commented on src/components/cart/cart-empty/CartEmpty.jsx
> +        <CartX />
I think it would have been better to call it EmptyCart. This is confusing.