migrate to redux - integrated reducers, actions and store/state
pandacover/tekion-menu pull request #4
Opened 2023-03-07 10:34 UTC by pandacover

2023-03-10 09:21 UTC, pandacover commented on src/redux/menu/menu.reducers.js
> +import MockData from "../../mock-data";
done

2023-03-10 09:22 UTC, pandacover commented on src/pages/CartPage.jsx
> +    reset();
done

2023-03-10 09:22 UTC, pandacover commented on src/components/menu/menu.jsx
> +    initMenuDispatched: (initMenuItems) => dispatch(initMenu(initMenuItems)),
done

2023-03-10 09:23 UTC, pandacover commented on src/components/menu/cart-icon/CartIcon.jsx
>    const isTotalCountVisible = useMemo(() => totalCount > 0, [totalCount]);
done, calculated cart size from the already connected parent component (Menu) and passed it as the props

2023-03-10 09:23 UTC, pandacover commented on src/components/menu/MenuAction.jsx
> +    addItem: (item) => dispatch(addItem(item)),
done. renamed to addItemDispatched

2023-03-10 09:24 UTC, pandacover commented on src/components/menu/MenuAction.jsx
> +  if (!cart.find((el) => el.id === id)) return <AddButton onAdd={onAdd} />;
done, used the helper function from findElement.helper.js

2023-03-10 09:26 UTC, pandacover commented on src/components/menu/MenuAction.jsx
> +    const timeoutId = setTimeout(() => updateLocalStorage(), 100);
since updating the localstorage without some break-time seems to be causing some issues.

2023-03-10 09:27 UTC, pandacover commented on src/components/menu/MenuAction.jsx
> +      removeItem(item);
I don't understand, I have not passed the event object to the store.

2023-03-10 09:28 UTC, pandacover commented on src/redux/cart/cart.reducers.js
> +const initialState = getCartFromLocalStorage();
done, called getCartFromLocalStorage() from a new reducer

2023-03-10 09:28 UTC, pandacover commented on src/redux/cart/cart.reducers.js
> +  const cartFromLocalStorage = localStorage.getItem("cart");
done

2023-03-10 09:28 UTC, pandacover commented on src/redux/cart/cart.creators.js
> +const cartCreators = {
done

2023-03-10 09:28 UTC, pandacover commented on src/pages/CartPage.jsx
> +  reset: global.noop,
done

2023-03-10 09:28 UTC, pandacover commented on src/pages/CartPage.jsx
> +            {isCartNotEmpty && (
done

2023-03-10 09:29 UTC, pandacover commented on src/hooks/useTotalCount.hook.js
> -    return acc + item.count;
done

2023-03-10 09:29 UTC, pandacover commented on src/hooks/useTotalAmount.hook.js
> +    return acc + item.quantity * item.price;
done

2023-03-10 09:29 UTC, pandacover commented on src/components/cart/cart.jsx
> +  cart: PropTypes.array,
done

2023-03-10 09:31 UTC, pandacover commented on src/components/cart/TableRow.jsx
> +  const PRICE = (typeof price === "number" && "$") + price;
seems to be adding "undefined". Changed to a regular ternary expression with false value = ""

2023-03-10 09:31 UTC, pandacover commented on src/components/cart/CartUtility.jsx
> +import { reset } from "../../redux/cart/cart.creators";
done

2023-03-10 09:32 UTC, pandacover commented on src/components/cart/ButtonLink.jsx
> +export default connect(mapStateToProps)(ButtonLink);
done, since the pay-button is checked at the upper level component instead (CartUtility), the cart state is not needed here now.

2023-03-10 09:44 UTC, pandacover commented on src/components/menu/MenuAction.jsx
> +  useEffect(() => {
done

2023-03-13 05:21 UTC, somethinglikejohn commented on src/components/button-link/ButtonLink.jsx
> +import React from "react";
we had discussed a format for imports in last PR. Try to follow that, imports will be more organised and consistent. that way.

2023-03-13 05:22 UTC, somethinglikejohn commented on src/components/button-link/ButtonLink.jsx
> +  const className = "button__link " + classname;
there is a lib classnames which will help in cases such as this. Just an FYI. For this project this is fine.

2023-03-13 05:23 UTC, somethinglikejohn commented on src/components/button-link/buttonLink.css
> +  color: #666;
we can organise colors in to a more standardized file when we work on the final project.

2023-03-13 05:23 UTC, somethinglikejohn commented on src/components/cart/CartUtility.jsx
> +import { calculatePrice } from "./helpers";
+1

2023-03-13 05:24 UTC, somethinglikejohn commented on src/components/cart/CartUtility.jsx
> +      navigate("/order-summary");
make sure you are aware of how this is handled without hooks as well.

2023-03-13 05:24 UTC, somethinglikejohn commented on src/components/cart/CartUtility.jsx
> +    return (
new line on line 45

2023-03-13 05:26 UTC, somethinglikejohn commented on src/components/cart/TableRow.jsx
> +  const PRICE = (typeof price === "number" ? "$" : "") + price;
why is this check needed ? - `typeof price === "number"`

2023-03-13 05:26 UTC, somethinglikejohn commented on src/components/cart/TableRow.jsx
>    return (
new line before return.

2023-03-13 05:27 UTC, somethinglikejohn commented on src/components/cart/TableRow.jsx
> +  const className = "cart__item " + classname;
better to name class names for what eg. TableRowContainer

2023-03-13 05:28 UTC, somethinglikejohn commented on src/components/cart/TableRow.jsx
> +  const className = "cart__item " + classname;
You can make cart_item a const and use the prefix across.  Just a suggestion.

2023-03-14 06:49 UTC, pandacover commented on src/components/cart/TableRow.jsx
> +  const PRICE = (typeof price === "number" ? "$" : "") + price;
so there are two types of elements which uses this component. One is table head and the other is table data.
if price is not number then the row is the table head, else it is a table data.

2023-03-14 06:52 UTC, pandacover commented on src/components/button-link/ButtonLink.jsx
> +import React from "react";
done

2023-03-14 06:52 UTC, pandacover commented on src/components/button-link/ButtonLink.jsx
> +  const className = "button__link " + classname;
I'll look into it.

2023-03-14 10:36 UTC, pandacover commented on src/components/cart/CartUtility.jsx
> +    return (
done

2023-03-14 10:37 UTC, pandacover commented on src/components/cart/TableRow.jsx
> +  const className = "cart__item " + classname;
Sorry, I don't understand

2023-03-14 10:37 UTC, pandacover commented on src/components/cart/TableRow.jsx
> +  const className = "cart__item " + classname;
noted.

2023-03-14 10:38 UTC, pandacover commented on src/components/cart/TableRow.jsx
>    return (
done

2023-03-14 10:40 UTC, pandacover commented on src/components/cart/CartUtility.jsx
> +      navigate("/order-summary");
with window.location = "/order-summary". Also with location.assign() and location.replace()

2023-03-14 10:41 UTC, pandacover commented on src/components/button-link/buttonLink.css
> +  color: #666;
understood

2023-03-15 05:38 UTC, pandacover commented on src/components/cart/TableRow.jsx
> +  const className = "cart__item " + classname;
done

2023-03-15 09:23 UTC, somethinglikejohn requested changes

2023-03-15 09:49 UTC, pandacover commented on src/pages/cart-page/CartPage.jsx
> +  const RenderCleanCart = () => {
done

2023-03-15 09:49 UTC, pandacover commented on src/pages/cart-page/CartPage.jsx
> +      isCartNotEmpty && (
done

2023-03-15 09:49 UTC, pandacover commented on src/components/menu/menu.css
> +    gap: calc((100% - (200% / 2.1)));
done

2023-03-15 10:55 UTC, pandacover commented on src/components/menu/cart-icon/CartIcon.jsx
> +  const isTotalCountVisible = useMemo(() => totalCartSize > 0, [totalCartSize]);
understood

2023-03-15 11:05 UTC, pandacover commented on src/pages/cart-page/CartPage.jsx
> +      localStorage.removeItem("cart");
done

2023-03-15 11:08 UTC, pandacover commented on src/pages/cart-page/cart-redux/cart.reducers.js
> +  switch (action.type) {
done

2023-03-15 11:08 UTC, pandacover commented on src/pages/cart-page/CartPage.jsx
> +  const isCartNotEmpty = useMemo(() => cart.length > 0, [cart]);
done

2023-03-15 11:48 UTC, somethinglikejohn commented on src/pages/cart-page/cart-redux/cart.reducers.js
> +      const cartFromLocalStorage = getCartFromLocalStorage();
ideally, value of getCartFromLocalStorage() should be passed as payload.

2023-03-15 11:57 UTC, somethinglikejohn commented on src/components/menu/MenuAction.jsx
> +  return <EditButton dispatch={{ onAdd, onRemove }} quantity={quantity} />;
dispatch={{ onAdd, onRemove }} - it is better to have used two props

2023-03-15 12:00 UTC, somethinglikejohn commented on src/components/cart/TableRow.jsx
> +  const PRICE = (typeof price === "number" ? "$" : "") + price;
what if we want to use TableRow for another table tomorrow ?

2023-03-15 12:02 UTC, somethinglikejohn commented on public/index.html
> +    <title>Tekion Menu</title>
remove references to company name - this is public and it would be best to avoid such refs. This is just for training.

2023-03-15 12:11 UTC, somethinglikejohn commented on src/components/menu/MenuAction.jsx
> +    () => (cartItem ? cartItem.quantity : 0),
cartItem ? cartItem.quantity ?? 0 : 0

2023-03-15 12:13 UTC, somethinglikejohn commented on src/components/menu/MenuAction.jsx
> +    addItemDispatched: (item) => dispatch(addItem(item)),
addItemDispatched - this is confusing - here action is not dispatched yet - when executed it will dispatch.

2023-03-15 12:13 UTC, somethinglikejohn commented on src/components/menu/MenuAction.jsx
> +    addItemDispatched: (item) => dispatch(addItem(item)),
check for other files where this naming needs to be changed as well

2023-03-15 12:14 UTC, somethinglikejohn commented on src/components/menu/actions/EditButton.jsx
> +    onAdd: PropTypes.func,
this is confusing - better not to name prop as dispatch - it is usually found associated with react and we dont want anyone confusing themselves - bad for readability

2023-03-15 12:15 UTC, somethinglikejohn commented on src/components/menu/card.jsx
> +  const className = "card__type " + type;
cardTypeClassnames

2023-03-15 12:17 UTC, somethinglikejohn commented on src/components/menu/menu.jsx
> +      filterAllRef.current.checked = true;
filterAllRef?.current?.checked. - null checks

2023-03-15 12:19 UTC, somethinglikejohn commented on src/pages/cart-page/cart-redux/cart.reducers.js
> +        return [
const quantity = targetItem?.quantity || 0;


{ ...targetItem, quantity: quantity + 1 },

2023-03-15 12:20 UTC, somethinglikejohn commented on src/pages/cart-page/cart-redux/cart.reducers.js
> +          if (el.id === action.payload.item.id)
extract quantity from el outside return add any null checks and always keep the return object clean.

2023-03-15 12:22 UTC, somethinglikejohn commented on src/styles/orderSummary.css
> +.order__summary__header {
move this file to the folder for Order summary. We had discussed folder structures before. \Let us try to keep things consistent.

2023-03-16 12:05 UTC, pandacover commented on src/components/cart/TableRow.jsx
> +  const PRICE = (typeof price === "number" ? "$" : "") + price;
fix: moved the logic to the Component rendering TableRow and passed the value as "price";

2023-03-16 12:05 UTC, pandacover commented on src/components/menu/MenuAction.jsx
> +  return <EditButton dispatch={{ onAdd, onRemove }} quantity={quantity} />;
segregated as two different props

2023-03-16 12:05 UTC, pandacover commented on public/index.html
> +    <title>Tekion Menu</title>
removed

2023-03-16 12:05 UTC, pandacover commented on src/components/helpers/calculateQuantity.helper.js
> +const calculateQuantity = (array) => {
understood

2023-03-16 12:06 UTC, pandacover commented on src/components/menu/MenuAction.jsx
> +    () => (cartItem ? cartItem.quantity : 0),
understood

2023-03-16 12:06 UTC, pandacover commented on src/components/menu/MenuAction.jsx
> +    addItemDispatched: (item) => dispatch(addItem(item)),
took your previous advice and changed it to addItemAction and so on.

2023-03-16 12:09 UTC, pandacover commented on src/components/menu/menu.jsx
> +      filterAllRef.current.checked = true;
removed ref, had some issues which needed extra unnecessary logic - needed "useEffect" since filterAllRef would always be null - while I needed this to work only once, when the component loaded - which it didn't.
instead checked it inside the filter component.

2023-03-16 12:10 UTC, pandacover commented on src/pages/cart-page/cart-redux/cart.reducers.js
> +        return [
done

2023-03-16 12:10 UTC, pandacover commented on src/pages/cart-page/cart-redux/cart.reducers.js
> +          if (el.id === action.payload.item.id)
done

2023-03-16 12:10 UTC, pandacover commented on src/styles/orderSummary.css
> +.order__summary__header {
done, wasn't aware of it.

2023-03-17 09:14 UTC, somethinglikejohn approved these changes

2023-03-17 09:15 UTC, merged